PR: stat_svc
AndreyAFedotov/java-explore-with-me pull request #1
Opened 2023-10-15 15:52 UTC by AndreyAFedotov

2023-10-16 18:04 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев в коде

2023-10-16 18:04 UTC, Frilock commented on ewm-stats/dto/pom.xml
> +            <version>2.15.1</version>
Смотрите, у вас многомодульный проект, поэтому должна быть 1 точка добавления зависимостей, сделайте в корневом pom файле секцию dependencyManager и добавляйте зависимости с версиями там, а в тех модулях где они вам нужны можно будет подключать уже без указания версии. Это позволит упростить проект в часте обновления/удаления зависимостей

2023-10-16 18:04 UTC, Frilock commented on ewm-stats/dto/src/main/java/ru/practicum/StatsDtoResponse.java
> +
Лишний пропуск

2023-10-16 18:04 UTC, Frilock commented on ewm-stats/stats-client/src/main/java/ru/practicum/BaseClient.java
> +            if (parameters != null) {
Можно заменить на тернарник, будет компактнее

2023-10-16 18:04 UTC, Frilock commented on ewm-stats/stats-server/src/main/java/ru/practicum/controller/StatsController.java
> +        log.info("Create Hit");
Добавляйте в лог какие то уникальные данные, а то в чем его смысл иначе?

2023-10-16 18:04 UTC, Frilock commented on ewm-stats/stats-server/src/main/java/ru/practicum/model/App.java
> +    @Column(name = "name")
Указывайте тут размерность, которую задаете в скрипте

2023-10-16 18:04 UTC, Frilock commented on ewm-stats/stats-server/src/main/java/ru/practicum/model/Hit.java
> +    @NotBlank
Лучше такую валидацию использовать на dto,  а тут указывать флаг nullable = false, в аннотации column

2023-10-16 18:06 UTC, AndreyAFedotov commented on ewm-main/pom.xml
> +
Исправил

2023-10-16 18:07 UTC, AndreyAFedotov commented on ewm-stats/dto/src/main/java/ru/practicum/StatsDtoResponse.java
> +
Исправил

2023-10-16 18:13 UTC, AndreyAFedotov commented on ewm-stats/stats-client/src/main/java/ru/practicum/BaseClient.java
> +            if (parameters != null) {
Я конечно поправил... Но проще он выглядеть не стал, как мне кажется ))

2023-10-16 18:16 UTC, AndreyAFedotov commented on ewm-stats/stats-server/src/main/java/ru/practicum/controller/StatsController.java
> +        log.info("Create Hit");
Я конечно исправил, добавил данных. Но вообще, следующей строкой в логе, был бы отчёт с ID созданной записи. Её бы отправил сервис.

2023-10-16 18:18 UTC, AndreyAFedotov commented on ewm-stats/stats-server/src/main/java/ru/practicum/model/App.java
> +    @Column(name = "name")
Исправил

2023-10-16 18:36 UTC, AndreyAFedotov commented on ewm-stats/dto/pom.xml
> +            <version>2.15.1</version>
Сейчас попытался вчитаться, что из себя представляет Dependency Management. С наскока не получилось осилить... В курсе нам про него ни слова не говорили, обещаю освоить. А эта зависимость во всём проекте есть только в этом единственном месте.

2023-10-17 04:54 UTC, Frilock commented on ewm-stats/stats-server/src/main/java/ru/practicum/controller/StatsController.java
> +        log.info("Create Hit");
тогда какой смысл от этого лога, если следующий будет информативнее

2023-10-17 04:55 UTC, Frilock approved these changes
Принято, но с dependencyManager лучше разобраться

2023-10-17 04:55 UTC, Frilock commented on ewm-stats/stats-client/src/main/java/ru/practicum/BaseClient.java
> +            shareitServerResponse = (parameters != null) ?
Так вы сразу делайте ResponseEntity<Object> shareitServerResponse =

2023-10-17 08:12 UTC, merged