Main svc
AndreyAFedotov/java-explore-with-me pull request #2
Opened 2023-10-26 10:22 UTC by AndreyAFedotov

2023-10-27 05:29 UTC, Frilock requested changes
Добрый день, в целом все здорово, пара мелких комментариев и можно принимать

2023-10-27 05:29 UTC, Frilock commented on ewm-main/pom.xml
> +            <version>5.0.0</version>
хочется чтобы в приложении была одна точка добавления зависимостей. Такой обычно делают корневой pom файл. Там нужно сделать блок dependencyManager и добавлять те библиотеки которых нет в parent, а затем уже в других pom файлах подключать, но уже без указания версии. Кроме того, версии этих библиотек правильнее указывать в properties, поскольку pom файлы бывают довольно больших размеров и изменение версии может быть не такой простой задачей.

2023-10-27 05:29 UTC, Frilock commented on ewm-main/src/main/java/ru/practicum/category/controller/AdminCategoryController.java
> +@Validated
По моему лишняя аннотация

2023-10-27 05:29 UTC, Frilock commented on ewm-main/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        if (isCategoryExists(id)) {
Инвертируйте условие, это поможет избежать лишней вложенности в методе

2023-10-27 05:29 UTC, Frilock commented on ewm-main/src/main/java/ru/practicum/compilation/controller/AdminCompilationController.java
> +@Validated
Лишняя аннотация

2023-10-27 05:29 UTC, Frilock commented on ewm-main/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        if (compilationStorage.existsById(id)) {
Можно отказаться от вложенности, инвертировав условие

2023-10-27 05:29 UTC, Frilock commented on ewm-main/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +    public CompilationDtoResponseAll updateCompilationByAdmin(Long id, CompilationDtoUpdateRequest request) {
Транзакция над методом?

2023-10-27 05:29 UTC, Frilock commented on ewm-main/src/main/java/ru/practicum/event/EventStorage.java
> +
Лишняя пустая строка

2023-10-27 05:29 UTC, Frilock commented on ewm-main/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                if (!event.getState().equals(EventState.PENDING)) {
enum поля правильнее сравнивать через стандартные операторы != и ==, работать будет в любом случае, но стандартные операторы как минимум быстрее

2023-10-27 05:29 UTC, Frilock commented on ewm-main/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        if (request.getStateAction() != null) {
Конструкция из 3х if подряд считается не очень хорошей практикой, подумайте как можно упростить вложенность

2023-10-27 05:29 UTC, Frilock commented on ewm-main/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            doSort = Sort.by("eventDate");
Сортировку можно тоже в енам вынести

2023-10-27 05:29 UTC, Frilock commented on ewm-main/src/main/java/ru/practicum/user/service/UserServiceImpl.java
> +        List<User> users;
Можно заменить конструкцию на тернарное выражение, будет компактнее

2023-10-27 06:46 UTC, AndreyAFedotov commented on ewm-main/pom.xml
> +            <version>5.0.0</version>
Решено

2023-10-27 06:53 UTC, AndreyAFedotov commented on ewm-main/src/main/java/ru/practicum/category/controller/AdminCategoryController.java
> +@Validated
Какая? Без @RequiredArgsConstructor будет проблема с подключением сервиса. Логирование тоже на месте. А без @Validated не будут работать аннотации @Valid в сигнатурах методов.

2023-10-27 06:57 UTC, AndreyAFedotov commented on ewm-main/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        if (isCategoryExists(id)) {
Исправил

2023-10-27 06:58 UTC, AndreyAFedotov commented on ewm-main/src/main/java/ru/practicum/compilation/controller/AdminCompilationController.java
> +@Validated
Этот вопрос описал выше

2023-10-27 07:05 UTC, AndreyAFedotov commented on ewm-main/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        if (compilationStorage.existsById(id)) {
Исправил

2023-10-27 07:08 UTC, AndreyAFedotov commented on ewm-main/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +    public CompilationDtoResponseAll updateCompilationByAdmin(Long id, CompilationDtoUpdateRequest request) {
Не понял вопроса. Класс аннотирован @Transactional . Считал, что этого достаточно. Чем выделяется этот метод?

2023-10-27 07:08 UTC, AndreyAFedotov commented on ewm-main/src/main/java/ru/practicum/event/EventStorage.java
> +
Исправил

2023-10-27 07:12 UTC, AndreyAFedotov commented on ewm-main/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                if (!event.getState().equals(EventState.PENDING)) {
Буквально на днях у нас с одногруппником вышел спор на эту тему, потом я нашёл вот эту статью: https://tproger.ru/articles/comparing-enums-in-java . Стало понятно, что да, "по классике" будет вернее. Хоть и такой подход ошибкой не будет. Этот момент я для себя усвоил. Но что бы не переделывать все условия в этом проекте, решил для единообразия оставить так. В будущем буду делать "по науке" :)

2023-10-27 07:21 UTC, AndreyAFedotov commented on ewm-main/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        if (request.getStateAction() != null) {
Упростил

2023-10-27 07:37 UTC, AndreyAFedotov commented on ewm-main/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            doSort = Sort.by("eventDate");
Реализовал

2023-10-27 07:51 UTC, AndreyAFedotov commented on ewm-main/src/main/java/ru/practicum/user/service/UserServiceImpl.java
> +        List<User> users;
Исправил

2023-10-28 12:22 UTC, Frilock commented on ewm-main/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +    public CompilationDtoResponseAll updateCompilationByAdmin(Long id, CompilationDtoUpdateRequest request) {
Да вы правы, не заметил аннотацию над классом.

2023-10-28 12:23 UTC, Frilock commented on ewm-main/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                if (!event.getState().equals(EventState.PENDING)) {
Окей, конечно, особой разницы нет, просто вам условный sonarcude вврнинг выласт

2023-10-28 12:26 UTC, Frilock commented on ewm-main/src/main/java/ru/practicum/category/controller/AdminCategoryController.java
> +@Validated
я в данном случае про аннотацию valid - https://struchkov.dev/blog/ru/spring-boot-validation/

2023-10-28 12:27 UTC, Frilock approved these changes
Добрый день, работу принимаю, отлично потрудились на курсе, на часть вопросов вам ответил, но думаю это все не критично. Удачи в дальнейшем

2023-10-28 13:52 UTC, merged